import Foundation

/// 文案
enum AllStr {
    // MARK: - Error
    static let errorServerUnavailable = NSLocalizedString("error.serverUnavailable", value: "Server sedang sibuk, silakan coba lagi nanti", comment: "")

    // MARK: - Launch
    static let launchAppName = NSLocalizedString("launch.appName", value: "Catat DanaKu", comment: "")
    static let launchTagline = NSLocalizedString("launch.tagline", value: "Catat pengeluaran dengan mudah", comment: "")

    // MARK: - Privacy
    static let privacyAgree = NSLocalizedString("privacy.agree", value: "Setuju", comment: "")
    static let privacyDisagree = NSLocalizedString("privacy.disagree", value: "Tidak Setuju", comment: "")
    static let privacyAlertMessage = NSLocalizedString("privacy.alert", value: "Anda harus menyetujui kebijakan privasi untuk melanjutkan", comment: "")
    static let privacyAlertOK = NSLocalizedString("privacy.alertOK", value: "OK", comment: "")
    static let privacyDescription = NSLocalizedString("privacy.description", value: "Harap baca dan setujui kebijakan privasi berikut dengan saksama.", comment: "")
    static let privacyToastWait = NSLocalizedString("privacy.toastWait", value: "Harap tunggu hingga perjanjian privasi selesai dimuat.", comment: "")

    // MARK: - Login
    static let loginPhoneHint = NSLocalizedString("login.phoneHint", value: "Masukkan no. ponsel", comment: "")
    static let loginCodeHint = NSLocalizedString("login.codeHint", value: "Kode verifikasi", comment: "")
    static let loginSendCode = NSLocalizedString("login.sendCode", value: "Kirim Kode", comment: "")
    static let loginWaLogin = NSLocalizedString("login.waLogin", value: "Kirim kode via WhatsApp", comment: "")
    static let loginSmsLogin = NSLocalizedString("login.smsLogin", value: "Kirim kode via SMS", comment: "")
    static let loginWaHint = NSLocalizedString("login.waHint", value: "*Kode verifikasi akan dikirim via WhatsApp.", comment: "")
    static let loginSentToSms = NSLocalizedString("login.sentToSms", value: "Kode verifikasi telah dikirim ke SMS Anda.", comment: "")
    static let loginSentToWa = NSLocalizedString("login.sentToWa", value: "Kode verifikasi telah dikirim ke WhatsApp Anda.", comment: "")
    static let loginResendViaWa = NSLocalizedString("login.resendViaWa", value: "Tidak menerima kode? Kirim via WhatsApp.", comment: "")
    static let loginResendViaSms = NSLocalizedString("login.resendViaSms", value: "Tidak menerima kode? Kirim via SMS.", comment: "")
    static let loginPrivacyPrefix = NSLocalizedString("login.privacyPrefix", value: "Pastikan Anda menyetujui ", comment: "")
    static let loginPrivacyLink = NSLocalizedString("login.privacyLink", value: "kebijakan privasi", comment: "")
    static let loginPrivacySuffix = NSLocalizedString("login.privacySuffix", value: " kami", comment: "")
    static let loginInvalidPhone = NSLocalizedString("login.invalidPhone", value: "Silakan masukkan nomor ponsel yang valid.", comment: "")
    static let loginInvalidCode = NSLocalizedString("login.invalidCode", value: "Silakan masukkan kode verifikasi 4 digit.", comment: "")
    static let loginLoginButton = NSLocalizedString("login.loginButton", value: "Masuk", comment: "")
    static let loginTitle = NSLocalizedString("login.title", value: "Masuk atau Daftar", comment: "")
    static let loginCountryCode = NSLocalizedString("login.countryCode", value: "+62", comment: "")
    static let loginPrivacySheetTitle = NSLocalizedString("login.privacySheetTitle", value: "Kebijakan Privasi", comment: "")
    static let loginClose = NSLocalizedString("login.close", value: "Tutup", comment: "")

    // MARK: - Permission
    static let permissionCameraTitle = NSLocalizedString("permission.cameraTitle", value: "Izin Kamera", comment: "")
    static let permissionCameraMessage = NSLocalizedString("permission.cameraMessage", value: "Untuk memberikan layanan yang lebih baik, silakan buka Pengaturan untuk mengaktifkan semua izin. Terima kasih!", comment: "")
    static let permissionGo = NSLocalizedString("permission.go", value: "Buka Pengaturan", comment: "")
    static let permissionCancel = NSLocalizedString("permission.cancel", value: "Batal", comment: "")

    // MARK: - Common
    static let commonSave = NSLocalizedString("common.save", value: "Simpan", comment: "")
    static let commonCancel = NSLocalizedString("common.cancel", value: "Batal", comment: "")
    static let commonIncome = NSLocalizedString("common.income", value: "Pemasukan", comment: "")
    static let commonExpense = NSLocalizedString("common.expense", value: "Pengeluaran", comment: "")
    static let commonAmount = NSLocalizedString("common.amount", value: "Jumlah", comment: "")
    static let commonNote = NSLocalizedString("common.note", value: "Catatan", comment: "")
    static let commonLocation = NSLocalizedString("common.location", value: "Lokasi", comment: "")
    static let commonSaved = NSLocalizedString("common.saved", value: "Tersimpan!", comment: "")

    // MARK: - Home
    static let homeWelcome = NSLocalizedString("home.welcome", value: "Selamat datang,", comment: "")
    static let homeMonthlyBalance = NSLocalizedString("home.monthlyBalance", value: "Saldo Bulan Ini", comment: "")
    static let homeViewAnalysis = NSLocalizedString("home.viewAnalysis", value: "Lihat analisis", comment: "")
    static let homeMainFeatures = NSLocalizedString("home.mainFeatures", value: "Fitur Utama", comment: "")
    static let homeRecentTransactions = NSLocalizedString("home.recentTransactions", value: "Transaksi Terkini", comment: "")
    static let homeViewAll = NSLocalizedString("home.viewAll", value: "Lihat semua", comment: "")
    static let homeNoTransactions = NSLocalizedString("home.noTransactions", value: "Belum ada transaksi", comment: "")
    static let homeTabHome = NSLocalizedString("home.tabHome", value: "Beranda", comment: "")
    static let homeTabProfile = NSLocalizedString("home.tabProfile", value: "Saya", comment: "")
    static let homeFeatureRecord = NSLocalizedString("home.featureRecord", value: "Catat Transaksi", comment: "")
    static let homeFeatureReminder = NSLocalizedString("home.featureReminder", value: "Pengingat Cicilan", comment: "")
    static let homeFeatureCreditCard = NSLocalizedString("home.featureCreditCard", value: "Kartu Kredit", comment: "")
    static let homeFeatureEMI = NSLocalizedString("home.featureEMI", value: "Kalkulator EMI", comment: "")
    static let homeFeatureMaxLoan = NSLocalizedString("home.featureMaxLoan", value: "Batas Pinjaman", comment: "")
    static let homeFeatureExchange = NSLocalizedString("home.featureExchange", value: "Kurs Mata Uang", comment: "")
    static let homeFeatureAnalysis = NSLocalizedString("home.featureAnalysis", value: "Analisis Keuangan", comment: "")

    // MARK: - RecordTransaction
    static let recordTransactionTitle = NSLocalizedString("record.title", value: "Catat Transaksi", comment: "")
    static let recordTransactionSave = NSLocalizedString("record.save", value: "Simpan Transaksi", comment: "")
    static let recordTransactionLocationPlaceholder = NSLocalizedString("record.locationPlaceholder", value: "Tambah lokasi...", comment: "")
    static let recordTransactionNotePlaceholder = NSLocalizedString("record.notePlaceholder", value: "Tambah catatan...", comment: "")
    static let recordTransactionPhotoTitle = NSLocalizedString("record.photoTitle", value: "Foto Struk/Bukti", comment: "")
    static let recordTransactionPhotoAttached = NSLocalizedString("record.photoAttached", value: "Foto terlampir", comment: "")
    static let recordTransactionTakePhoto = NSLocalizedString("record.takePhoto", value: "Ambil / Pilih Foto", comment: "")
    static let recordTransactionCategory = NSLocalizedString("record.category", value: "Kategori", comment: "")
    static let recordTransactionSavedToast = NSLocalizedString("record.savedToast", value: "Tersimpan!", comment: "")

    // MARK: - TransactionDetail
    static let transactionDetailTitle = NSLocalizedString("detail.title", value: "Detail Transaksi", comment: "")
    static let transactionDetailType = NSLocalizedString("detail.type", value: "Tipe", comment: "")
    static let transactionDetailCategory = NSLocalizedString("detail.category", value: "Kategori", comment: "")
    static let transactionDetailAmount = NSLocalizedString("detail.amount", value: "Jumlah", comment: "")
    static let transactionDetailDate = NSLocalizedString("detail.date", value: "Tanggal", comment: "")
    static let transactionDetailLocation = NSLocalizedString("detail.location", value: "Lokasi", comment: "")
    static let transactionDetailNote = NSLocalizedString("detail.note", value: "Catatan", comment: "")
    static let transactionDetailPhoto = NSLocalizedString("detail.photo", value: "Foto Bukti", comment: "")

    // MARK: - Category
    // Expense
    static let categoryFood = NSLocalizedString("category.food", value: "Makanan", comment: "")
    static let categoryTransport = NSLocalizedString("category.transport", value: "Transportasi", comment: "")
    static let categoryShopping = NSLocalizedString("category.shopping", value: "Belanja", comment: "")
    static let categoryHealth = NSLocalizedString("category.health", value: "Kesehatan", comment: "")
    static let categoryEntertainment = NSLocalizedString("category.entertainment", value: "Hiburan", comment: "")
    static let categoryEducation = NSLocalizedString("category.education", value: "Pendidikan", comment: "")
    static let categoryUtilities = NSLocalizedString("category.utilities", value: "Utilitas", comment: "")
    static let categoryOtherExpense = NSLocalizedString("category.otherExpense", value: "Lainnya", comment: "")
    static let categoryGroceries = NSLocalizedString("category.groceries", value: "Sembako", comment: "")
    static let categoryHousing = NSLocalizedString("category.housing", value: "Perumahan/Sewa", comment: "")
    static let categoryCommunication = NSLocalizedString("category.communication", value: "Pulsa & Internet", comment: "")
    static let categoryFamily = NSLocalizedString("category.family", value: "Keluarga & Anak", comment: "")
    static let categoryInsurance = NSLocalizedString("category.insurance", value: "Asuransi", comment: "")
    static let categoryPets = NSLocalizedString("category.pets", value: "Hewan Peliharaan", comment: "")
    static let categorySubscriptions = NSLocalizedString("category.subscriptions", value: "Langganan", comment: "")
    static let categoryPersonalCare = NSLocalizedString("category.personalCare", value: "Perawatan Diri", comment: "")
    static let categoryGifts = NSLocalizedString("category.gifts", value: "Hadiah & Donasi", comment: "")
    static let categoryTravel = NSLocalizedString("category.travel", value: "Perjalanan/Wisata", comment: "")
    // Income
    static let categorySalary = NSLocalizedString("category.salary", value: "Gaji", comment: "")
    static let categoryInvestment = NSLocalizedString("category.investment", value: "Pendapatan Investasi", comment: "")
    static let categoryRental = NSLocalizedString("category.rental", value: "Aset/Pendapatan Sewa", comment: "")
    static let categoryPrize = NSLocalizedString("category.prize", value: "Kemenangan/Hadiah", comment: "")
    static let categoryProject = NSLocalizedString("category.project", value: "Proyek Jangka Pendek", comment: "")
    static let categoryBusiness = NSLocalizedString("category.business", value: "Pendapatan Bisnis", comment: "")
    static let categorySale = NSLocalizedString("category.sale", value: "Penjualan Barang", comment: "")
    static let categoryGift = NSLocalizedString("category.gift", value: "Uang Hadiah/Hibah", comment: "")
    static let categoryOtherIncome = NSLocalizedString("category.otherIncome", value: "Lainnya", comment: "")

    // MARK: - Reminder
    static let reminderTitle = NSLocalizedString("reminder.title", value: "Pengingat Cicilan", comment: "")
    static let reminderMonthlyTotal = NSLocalizedString("reminder.monthlyTotal", value: "Total Tagihan Bulan Ini", comment: "")
    static let reminderActiveCount = NSLocalizedString("reminder.activeCount", value: "pengingat aktif", comment: "")
    static let reminderNoReminders = NSLocalizedString("reminder.noReminders", value: "Belum ada pengingat", comment: "")
    static let reminderUrgent = NSLocalizedString("reminder.urgent", value: "Segera", comment: "")
    static let reminderPastDue = NSLocalizedString("reminder.pastDue", value: "Lewat jatuh tempo", comment: "")
    static let reminderAddTitle = NSLocalizedString("reminder.addTitle", value: "Tambah Pengingat Baru", comment: "")
    static let reminderNameLabel = NSLocalizedString("reminder.nameLabel", value: "Nama Tagihan", comment: "")
    static let reminderAmountLabel = NSLocalizedString("reminder.amountLabel", value: "Jumlah (Rp)", comment: "")
    static let reminderDueDateLabel = NSLocalizedString("reminder.dueDateLabel", value: "Tanggal Jatuh Tempo", comment: "")
    static let reminderNoteLabel = NSLocalizedString("reminder.noteLabel", value: "Keterangan", comment: "")
    static let reminderNamePlaceholder = NSLocalizedString("reminder.namePlaceholder", value: "Contoh: Cicilan KPR", comment: "")
    static let reminderAmountPlaceholder = NSLocalizedString("reminder.amountPlaceholder", value: "Contoh: 2000000", comment: "")
    static let reminderNotePlaceholder = NSLocalizedString("reminder.notePlaceholder", value: "Contoh: Bank BCA", comment: "")

    // MARK: - CreditCard
    static let creditCardTitle = NSLocalizedString("creditcard.title", value: "Kartu Kredit", comment: "")
    static let creditCardEmpty = NSLocalizedString("creditcard.empty", value: "Belum ada kartu tersimpan", comment: "")
    static let creditCardAddTitle = NSLocalizedString("creditcard.addTitle", value: "Tambah Kartu Baru", comment: "")
    static let creditCardNumberLabel = NSLocalizedString("creditcard.numberLabel", value: "Nomor Kartu", comment: "")
    static let creditCardBankLabel = NSLocalizedString("creditcard.bankLabel", value: "Nama Bank", comment: "")
    static let creditCardBankPlaceholder = NSLocalizedString("creditcard.bankPlaceholder", value: "Atau ketik nama bank...", comment: "")
    static let creditCardDueDateLabel = NSLocalizedString("creditcard.dueDateLabel", value: "Tanggal Jatuh Tempo", comment: "")
    static let creditCardPerMonth = NSLocalizedString("creditcard.perMonth", value: "setiap bulan", comment: "")
    static let creditCardDueLabel = NSLocalizedString("creditcard.dueLabel", value: "Jatuh tempo", comment: "")
    static let creditCardSave = NSLocalizedString("creditcard.save", value: "Simpan Kartu", comment: "")
    static let creditCardNumberPlaceholder = NSLocalizedString("creditcard.numberPlaceholder", value: "0000 0000 0000 0000", comment: "")
    static let creditCardDatePlaceholder = NSLocalizedString("creditcard.datePlaceholder", value: "15", comment: "")
    static let creditCardDateFormat = NSLocalizedString("creditcard.dateFormat", value: "Tgl %d", comment: "")

    // MARK: - EMI
    static let emiTitle = NSLocalizedString("emi.title", value: "Kalkulator EMI", comment: "")
    static let emiLoanLabel = NSLocalizedString("emi.loanLabel", value: "Jumlah Pinjaman (Rp)", comment: "")
    static let emiTenorLabel = NSLocalizedString("emi.tenorLabel", value: "Tenor (Bulan)", comment: "")
    static let emiRateLabel = NSLocalizedString("emi.rateLabel", value: "Suku Bunga Tahunan", comment: "")
    static let emiCalculate = NSLocalizedString("emi.calculate", value: "Hitung EMI", comment: "")
    static let emiMonthlyEMI = NSLocalizedString("emi.monthlyEMI", value: "Cicilan Per Bulan (EMI)", comment: "")
    static let emiTotalPayment = NSLocalizedString("emi.totalPayment", value: "Total Pembayaran", comment: "")
    static let emiTotalInterest = NSLocalizedString("emi.totalInterest", value: "Total Bunga", comment: "")
    static let emiFormula = NSLocalizedString("emi.formula", value: "Rumus EMI:", comment: "")
    static let emiLoanPlaceholder = NSLocalizedString("emi.loanPlaceholder", value: "Contoh: 50000000", comment: "")
    static let emiTenorPlaceholder = NSLocalizedString("emi.tenorPlaceholder", value: "Contoh: 24", comment: "")
    static let emiRatePlaceholder = NSLocalizedString("emi.ratePlaceholder", value: "Contoh: 12", comment: "")
    static let emiTenorSuffix = NSLocalizedString("emi.tenorSuffix", value: "bulan", comment: "")
    static let emiRateSuffix = NSLocalizedString("emi.rateSuffix", value: "% / tahun", comment: "")

    // MARK: - MaxLoan
    static let maxLoanTitle = NSLocalizedString("maxloan.title", value: "Batas Pinjaman Maks", comment: "")
    static let maxLoanPaymentLabel = NSLocalizedString("maxloan.paymentLabel", value: "Kemampuan Cicilan Per Bulan (Rp)", comment: "")
    static let maxLoanRateLabel = NSLocalizedString("maxloan.rateLabel", value: "Suku Bunga Tahunan", comment: "")
    static let maxLoanTenorLabel = NSLocalizedString("maxloan.tenorLabel", value: "Tenor Pinjaman", comment: "")
    static let maxLoanCalculate = NSLocalizedString("maxloan.calculate", value: "Hitung Batas Pinjaman", comment: "")
    static let maxLoanResultLabel = NSLocalizedString("maxloan.resultLabel", value: "Maksimum Pinjaman yang Bisa Diajukan", comment: "")
    static let maxLoanNote = NSLocalizedString("maxloan.note", value: "Catatan:", comment: "")
    static let maxLoanInfoTip = NSLocalizedString("maxloan.infoTip", value: "Masukkan kemampuan cicilan maksimum per bulan Anda untuk mengetahui berapa pinjaman yang bisa Anda ajukan.", comment: "")
    static let maxLoanResultSummary = NSLocalizedString("maxloan.resultSummary", value: "Dengan cicilan %@/bulan selama %@ bulan pada bunga %@%% per tahun", comment: "")
    static let maxLoanDisclaimer = NSLocalizedString("maxloan.disclaimer", value: "Hasil ini adalah estimasi berdasarkan perhitungan matematika. Bank mungkin memiliki kriteria persetujuan lain seperti skor kredit dan riwayat keuangan.", comment: "")
    static let maxLoanPaymentPlaceholder = NSLocalizedString("maxloan.paymentPlaceholder", value: "Contoh: 2000000", comment: "")
    static let maxLoanRatePlaceholder = NSLocalizedString("maxloan.ratePlaceholder", value: "Contoh: 12", comment: "")
    static let maxLoanTenorPlaceholder = NSLocalizedString("maxloan.tenorPlaceholder", value: "Contoh: 36", comment: "")
    static let maxLoanTenorSuffix = NSLocalizedString("maxloan.tenorSuffix", value: "bulan", comment: "")
    static let maxLoanRateSuffix = NSLocalizedString("maxloan.rateSuffix", value: "% / tahun", comment: "")

    // MARK: - ExchangeRate
    static let exchangeRateTitle = NSLocalizedString("exchange.title", value: "Kurs Mata Uang", comment: "")
    static let exchangeRateIdrLabel = NSLocalizedString("exchange.idrLabel", value: "Jumlah Rupiah (IDR)", comment: "")
    static let exchangeRateResultTitle = NSLocalizedString("exchange.resultTitle", value: "Hasil Konversi", comment: "")
    static let exchangeRateSelectCurrency = NSLocalizedString("exchange.selectCurrency", value: "Pilih Mata Uang", comment: "")
    static let exchangeRateDisclaimer = NSLocalizedString("exchange.disclaimer", value: "* Kurs bersifat indikatif dan dapat berubah sewaktu-waktu", comment: "")

    // MARK: - Analysis
    static let analysisTitle = NSLocalizedString("analysis.title", value: "Analisis Keuangan", comment: "")
    static let analysisTotalIncome = NSLocalizedString("analysis.totalIncome", value: "Total Pemasukan", comment: "")
    static let analysisTotalExpense = NSLocalizedString("analysis.totalExpense", value: "Total Pengeluaran", comment: "")
    static let analysisSavingsRate = NSLocalizedString("analysis.savingsRate", value: "Tingkat Tabungan", comment: "")
    static let analysisOfIncome = NSLocalizedString("analysis.ofIncome", value: "dari pemasukan", comment: "")
    static let analysisExpenseByCategory = NSLocalizedString("analysis.expenseByCategory", value: "Pengeluaran per Kategori", comment: "")
    static let analysisIncomeVsExpense = NSLocalizedString("analysis.incomeVsExpense", value: "Pemasukan vs Pengeluaran", comment: "")
    static let analysisTopExpenses = NSLocalizedString("analysis.topExpenses", value: "Pengeluaran Terbesar", comment: "")
    static let analysisNoExpenseData = NSLocalizedString("analysis.noExpenseData", value: "Belum ada data pengeluaran", comment: "")
    static let analysisNoExpenseDataMonth = NSLocalizedString("analysis.noExpenseDataMonth", value: "Belum ada data pengeluaran bulan ini", comment: "")

    // MARK: - Profile
    static let profileTransactions = NSLocalizedString("profile.transactions", value: "Transaksi", comment: "")
    static let profileCreditCards = NSLocalizedString("profile.creditCards", value: "Kartu Kredit", comment: "")
    static let profileReminders = NSLocalizedString("profile.reminders", value: "Pengingat", comment: "")
    static let profileContactUs = NSLocalizedString("profile.contactUs", value: "Hubungi Kami", comment: "")
    static let profilePrivacy = NSLocalizedString("profile.privacy", value: "Kebijakan Privasi", comment: "")
    static let profileRateApp = NSLocalizedString("profile.rateApp", value: "Beri Rating Aplikasi", comment: "")
    static let profileSettings = NSLocalizedString("profile.settings", value: "Pengaturan", comment: "")
    static let profileChangeNameTitle = NSLocalizedString("profile.changeNameTitle", value: "Ubah Nama", comment: "")
    static let profileNamePlaceholder = NSLocalizedString("profile.namePlaceholder", value: "Nama Anda", comment: "")
    static let profileNameMessage = NSLocalizedString("profile.nameMessage", value: "Masukkan nama panggilan Anda", comment: "")
    static let profileAvatarTitle = NSLocalizedString("profile.avatarTitle", value: "Foto Profil", comment: "")
    static let profileTakePhoto = NSLocalizedString("profile.takePhoto", value: "Ambil Foto", comment: "")
    static let profilePickGallery = NSLocalizedString("profile.pickGallery", value: "Pilih dari Galeri", comment: "")

    // MARK: - Settings
    static let settingsTitle = NSLocalizedString("settings.title", value: "Pengaturan", comment: "")
    static let settingsAppInfo = NSLocalizedString("settings.appInfo", value: "Informasi", comment: "")
    static let settingsVersion = NSLocalizedString("settings.version", value: "Versi Aplikasi", comment: "")
    static let settingsDangerZone = NSLocalizedString("settings.dangerZone", value: "Zona Berbahaya", comment: "")
    static let settingsLogout = NSLocalizedString("settings.logout", value: "Keluar dari Akun", comment: "")
    static let settingsDeleteData = NSLocalizedString("settings.deleteData", value: "Hapus Data Akun", comment: "")
    static let settingsLogoutTitle = NSLocalizedString("settings.logoutTitle", value: "Keluar dari Akun?", comment: "")
    static let settingsLogoutMessage = NSLocalizedString("settings.logoutMessage", value: "Anda akan keluar dari akun CatatDanaKu. Data Anda tetap tersimpan dengan aman.", comment: "")
    static let settingsDeleteTitle = NSLocalizedString("settings.deleteTitle", value: "⚠️ Hapus Data Akun?", comment: "")
    static let settingsDeleteMessage = NSLocalizedString("settings.deleteMessage", value: "Tindakan ini tidak dapat dibatalkan. Semua data transaksi, pengingat, dan kartu kredit Anda akan dihapus secara permanen.", comment: "")
    static let settingsDeleteSecondTitle = NSLocalizedString("settings.deleteSecondTitle", value: "⚠️ Konfirmasi Ulang", comment: "")
    static let settingsDeleteSecondMessage = NSLocalizedString("settings.deleteSecondMessage", value: "Penghapusan data tidak dapat dibatalkan, harap konfirmasi lagi.", comment: "")
    static let settingsLogoutConfirm = NSLocalizedString("settings.logoutConfirm", value: "Keluar", comment: "")
    static let settingsDeleteConfirm = NSLocalizedString("settings.deleteConfirm", value: "Hapus Akun", comment: "")
    static let settingsDeleteSecondConfirm = NSLocalizedString("settings.deleteSecondConfirm", value: "Hapus Permanen", comment: "")
    static let settingsAlreadyLatest = NSLocalizedString("settings.alreadyLatest", value: "Sudah versi terbaru", comment: "")

    // MARK: - Contact
    static let contactTitle = NSLocalizedString("contact.title", value: "Hubungi Kami", comment: "")
    static let contactMessageLabel = NSLocalizedString("contact.messageLabel", value: "Pesan", comment: "")
    static let contactAttachmentLabel = NSLocalizedString("contact.attachmentLabel", value: "Lampiran (opsional)", comment: "")
    static let contactAddImage = NSLocalizedString("contact.addImage", value: "Tambah Gambar", comment: "")
    static let contactContactPlaceholder = NSLocalizedString("contact.contactPlaceholder", value: "Masukkan email atau WhatsApp Anda", comment: "")
    static let contactContactLabel = NSLocalizedString("contact.contactLabel", value: "Email / WhatsApp", comment: "")
    static let contactSubmit = NSLocalizedString("contact.submit", value: "Kirim", comment: "")
    static let contactSubmitting = NSLocalizedString("contact.submitting", value: "Mengirim...", comment: "")
    static let contactSuccessMessage = NSLocalizedString("contact.successMessage", value: "Terkirim! Kami akan segera menghubungi Anda.", comment: "")
    static let contactAttachmentSheet = NSLocalizedString("contact.attachmentSheet", value: "Lampiran", comment: "")
    static let contactVideoLabel = NSLocalizedString("contact.videoLabel", value: "Video (opsional)", comment: "")
    static let contactAddVideo = NSLocalizedString("contact.addVideo", value: "Tambah Video", comment: "")
    static let contactVideoSheet = NSLocalizedString("contact.videoSheet", value: "Video", comment: "")
    static let contactRecordVideo = NSLocalizedString("contact.recordVideo", value: "Rekam Video", comment: "")
    static let contactPickVideo = NSLocalizedString("contact.pickVideo", value: "Pilih dari Galeri", comment: "")
}
