import Foundation

/// 文案
enum AllStr {
    // MARK: - e
    static let eSu = NSLocalizedString("e.Su", value: "Layanan sedang ramai, coba lagi nanti ya", comment: "")

    // MARK: - la
    static let laAn = NSLocalizedString("la.An", value: "Catat DanaKu", comment: "")
    static let laT = NSLocalizedString("la.T", value: "Pantau keuanganmu, simpel aja", comment: "")

    // MARK: - pv
    static let pvA = NSLocalizedString("pv.A", value: "Setuju", comment: "")
    static let pvDi = NSLocalizedString("pv.Di", value: "Tidak Setuju", comment: "")
    static let pvAm = NSLocalizedString("pv.Am", value: "Setujui dulu kebijakan privasi supaya bisa lanjut, ya", comment: "")
    static let pvAo = NSLocalizedString("pv.Ao", value: "OK", comment: "")
    static let pvDe = NSLocalizedString("pv.De", value: "Baca dan setujui dulu kebijakan privasi di bawah ini, ya.", comment: "")
    static let pvTw = NSLocalizedString("pv.Tw", value: "Sebentar ya, halaman privasi masih dimuat.", comment: "")

    // MARK: - lg
    static let lgPh = NSLocalizedString("lg.Ph", value: "Nomor HP kamu", comment: "")
    static let lgCh = NSLocalizedString("lg.Ch", value: "Kode OTP", comment: "")
    static let lgSc = NSLocalizedString("lg.Sc", value: "Minta Kode", comment: "")
    static let lgWl = NSLocalizedString("lg.Wl", value: "Kirim kode lewat WhatsApp", comment: "")
    static let lgSl = NSLocalizedString("lg.Sl", value: "Kirim kode lewat SMS", comment: "")
    static let lgWh = NSLocalizedString("lg.Wh", value: "*Kode verifikasi bakal dikirim lewat WhatsApp ya.", comment: "")
    static let lgSs = NSLocalizedString("lg.Ss", value: "Kode sudah dikirim ke SMS kamu, cek ya.", comment: "")
    static let lgSw = NSLocalizedString("lg.Sw", value: "Kode sudah dikirim ke WhatsApp kamu, cek ya.", comment: "")
    static let lgRw = NSLocalizedString("lg.Rw", value: "Belum dapat kode? Coba lewat WhatsApp aja.", comment: "")
    static let lgRs = NSLocalizedString("lg.Rs", value: "Belum dapat kode? Coba lewat SMS aja.", comment: "")
    static let lgPp = NSLocalizedString("lg.Pp", value: "Pastikan kamu setuju dengan ", comment: "")
    static let lgPl = NSLocalizedString("lg.Pl", value: "kebijakan privasi", comment: "")
    static let lgPs = NSLocalizedString("lg.Ps", value: " kami", comment: "")
    static let lgIp = NSLocalizedString("lg.Ip", value: "Masukkan nomor HP yang benar dulu ya.", comment: "")
    static let lgIc = NSLocalizedString("lg.Ic", value: "Isi kode verifikasi 4 digit yang dikirim ya.", comment: "")
    static let lgLb = NSLocalizedString("lg.Lb", value: "Masuk", comment: "")
    static let lgT = NSLocalizedString("lg.T", value: "Login / Daftar", comment: "")
    static let lgCc = NSLocalizedString("lg.Cc", value: "+62", comment: "")
    static let lgPst = NSLocalizedString("lg.Pst", value: "Kebijakan Privasi", comment: "")
    static let lgC = NSLocalizedString("lg.C", value: "Tutup", comment: "")

    // MARK: - pm
    static let pmCt = NSLocalizedString("pm.Ct", value: "Akses Kamera", comment: "")
    static let pmCm = NSLocalizedString("pm.Cm", value: "Supaya aplikasi berjalan maksimal, buka Pengaturan dan aktifkan izin kameranya dulu ya. Makasih!", comment: "")
    static let pmG = NSLocalizedString("pm.G", value: "Ke Pengaturan", comment: "")
    static let pmC = NSLocalizedString("pm.C", value: "Gak Jadi", comment: "")

    // MARK: - cm
    static let cmS = NSLocalizedString("cm.S", value: "Simpen", comment: "")
    static let cmC = NSLocalizedString("cm.C", value: "Gak Jadi", comment: "")
    static let cmI = NSLocalizedString("cm.I", value: "Uang Masuk", comment: "")
    static let cmE = NSLocalizedString("cm.E", value: "Uang Keluar", comment: "")
    static let cmA = NSLocalizedString("cm.A", value: "Nominal", comment: "")
    static let cmN = NSLocalizedString("cm.N", value: "Keterangan", comment: "")
    static let cmL = NSLocalizedString("cm.L", value: "Tempat", comment: "")
    static let cmSd = NSLocalizedString("cm.Sd", value: "Tersimpan! ✅", comment: "")

    // MARK: - h
    static let hW = NSLocalizedString("h.W", value: "Selamat datang,", comment: "")
    static let hMb = NSLocalizedString("h.Mb", value: "Saldo Bulan Ini 💰", comment: "")
    static let hVa = NSLocalizedString("h.Va", value: "Cek analisis →", comment: "")
    static let hMf = NSLocalizedString("h.Mf", value: "Layanan Kami", comment: "")
    static let hRt = NSLocalizedString("h.Rt", value: "Transaksi Terbaru", comment: "")
    static let hVal = NSLocalizedString("h.Val", value: "Lihat semua →", comment: "")
    static let hNt = NSLocalizedString("h.Nt", value: "Belum ada transaksi nih", comment: "")
    static let hTh = NSLocalizedString("h.Th", value: "Beranda", comment: "")
    static let hTp = NSLocalizedString("h.Tp", value: "Saya", comment: "")
    static let hFr = NSLocalizedString("h.Fr", value: "Input Transaksi", comment: "")
    static let hFmr = NSLocalizedString("h.Fmr", value: "Reminder Cicilan", comment: "")
    static let hFcc = NSLocalizedString("h.Fcc", value: "Kartu Kredit", comment: "")
    static let hFem = NSLocalizedString("h.Fem", value: "Kalkulator EMI", comment: "")
    static let hFml = NSLocalizedString("h.Fml", value: "Batas Pinjaman", comment: "")
    static let hFex = NSLocalizedString("h.Fex", value: "Kurs Mata Uang", comment: "")
    static let hFan = NSLocalizedString("h.Fan", value: "Analisis Keuangan 📈", comment: "")

    // MARK: - rt
    static let rtT = NSLocalizedString("rt.T", value: "Input Transaksi", comment: "")
    static let rtS = NSLocalizedString("rt.S", value: "Simpen Transaksi", comment: "")
    static let rtLp = NSLocalizedString("rt.Lp", value: "Isi tempat...", comment: "")
    static let rtNp = NSLocalizedString("rt.Np", value: "Tulis keterangan...", comment: "")
    static let rtPt = NSLocalizedString("rt.Pt", value: "Lampirkan Bukti", comment: "")
    static let rtPa = NSLocalizedString("rt.Pa", value: "Bukti terlampir ✅", comment: "")
    static let rtTp = NSLocalizedString("rt.Tp", value: "Jepret / Cari Foto", comment: "")
    static let rtC = NSLocalizedString("rt.C", value: "Kategori 📂", comment: "")
    static let rtSt = NSLocalizedString("rt.St", value: "Tersimpan! ✅", comment: "")

    // MARK: - td
    static let tdT = NSLocalizedString("td.T", value: "Rincian Transaksi", comment: "")
    static let tdTy = NSLocalizedString("td.Ty", value: "Jenis", comment: "")
    static let tdC = NSLocalizedString("td.C", value: "Kategori 📂", comment: "")
    static let tdA = NSLocalizedString("td.A", value: "Nominal", comment: "")
    static let tdDa = NSLocalizedString("td.Da", value: "Tgl", comment: "")
    static let tdL = NSLocalizedString("td.L", value: "Tempat", comment: "")
    static let tdN = NSLocalizedString("td.N", value: "Keterangan", comment: "")
    static let tdPh = NSLocalizedString("td.Ph", value: "Lampiran Bukti", comment: "")

    // MARK: - ct
    // Expense
    static let ctFo = NSLocalizedString("ct.Fo", value: "Makanan", comment: "")
    static let ctTr = NSLocalizedString("ct.Tr", value: "Transportasi", comment: "")
    static let ctSh = NSLocalizedString("ct.Sh", value: "Belanja", comment: "")
    static let ctHe = NSLocalizedString("ct.He", value: "Kesehatan", comment: "")
    static let ctEn = NSLocalizedString("ct.En", value: "Hiburan", comment: "")
    static let ctEd = NSLocalizedString("ct.Ed", value: "Pendidikan", comment: "")
    static let ctUt = NSLocalizedString("ct.Ut", value: "Utilitas", comment: "")
    static let ctOe = NSLocalizedString("ct.Oe", value: "Lainnya", comment: "")
    static let ctGr = NSLocalizedString("ct.Gr", value: "Sembako", comment: "")
    static let ctHo = NSLocalizedString("ct.Ho", value: "Perumahan/Sewa", comment: "")
    static let ctCo = NSLocalizedString("ct.Co", value: "Pulsa & Internet", comment: "")
    static let ctFa = NSLocalizedString("ct.Fa", value: "Keluarga & Anak", comment: "")
    static let ctIn = NSLocalizedString("ct.In", value: "Asuransi", comment: "")
    static let ctPe = NSLocalizedString("ct.Pe", value: "Hewan Peliharaan", comment: "")
    static let ctSu = NSLocalizedString("ct.Su", value: "Langganan", comment: "")
    static let ctPc = NSLocalizedString("ct.Pc", value: "Perawatan Diri", comment: "")
    static let ctGi = NSLocalizedString("ct.Gi", value: "Hadiah & Donasi", comment: "")
    static let ctTv = NSLocalizedString("ct.Tv", value: "Perjalanan/Wisata", comment: "")
    // Income
    static let ctSa = NSLocalizedString("ct.Sa", value: "Gaji", comment: "")
    static let ctIv = NSLocalizedString("ct.Iv", value: "Pendapatan Investasi", comment: "")
    static let ctRe = NSLocalizedString("ct.Re", value: "Aset/Pendapatan Sewa", comment: "")
    static let ctPr = NSLocalizedString("ct.Pr", value: "Kemenangan/Hadiah", comment: "")
    static let ctPj = NSLocalizedString("ct.Pj", value: "Proyek Jangka Pendek", comment: "")
    static let ctBu = NSLocalizedString("ct.Bu", value: "Pendapatan Bisnis", comment: "")
    static let ctSl = NSLocalizedString("ct.Sl", value: "Penjualan Barang", comment: "")
    static let ctGf = NSLocalizedString("ct.Gf", value: "Uang Hadiah/Hibah", comment: "")
    static let ctOi = NSLocalizedString("ct.Oi", value: "Lainnya", comment: "")

    // MARK: - rm
    static let rmT = NSLocalizedString("rm.T", value: "Reminder Cicilan", comment: "")
    static let rmMt = NSLocalizedString("rm.Mt", value: "Total Cicilan Bulan Ini", comment: "")
    static let rmAc = NSLocalizedString("rm.Ac", value: "reminder aktif", comment: "")
    static let rmNr = NSLocalizedString("rm.Nr", value: "Belum ada pengingat nih", comment: "")
    static let rmUr = NSLocalizedString("rm.Ur", value: "Urgent 🔴", comment: "")
    static let rmPd = NSLocalizedString("rm.Pd", value: "Sudah lewat deadline", comment: "")
    static let rmAt = NSLocalizedString("rm.At", value: "Buat Reminder Baru", comment: "")
    static let rmNl = NSLocalizedString("rm.Nl", value: "Nama Cicilan", comment: "")
    static let rmAl = NSLocalizedString("rm.Al", value: "Jumlah (Rp)", comment: "")
    static let rmDl = NSLocalizedString("rm.Dl", value: "Tanggal Jatuh Tempo", comment: "")
    static let rmNte = NSLocalizedString("rm.Nte", value: "Keterangan", comment: "")
    static let rmNp = NSLocalizedString("rm.Np", value: "Contoh: Cicilan KPR", comment: "")
    static let rmAp = NSLocalizedString("rm.Ap", value: "Contoh: 2000000", comment: "")
    static let rmNtp = NSLocalizedString("rm.Ntp", value: "Contoh: Bank BCA", comment: "")

    // MARK: - cc
    static let ccT = NSLocalizedString("cc.T", value: "Kartu Kredit", comment: "")
    static let ccEm = NSLocalizedString("cc.Em", value: "Belum ada kartu yang disimpan nih", comment: "")
    static let ccAt = NSLocalizedString("cc.At", value: "Buat Kartu Baru", comment: "")
    static let ccNl = NSLocalizedString("cc.Nl", value: "No. Kartu", comment: "")
    static let ccBl = NSLocalizedString("cc.Bl", value: "Bank", comment: "")
    static let ccBp = NSLocalizedString("cc.Bp", value: "Atau tulis nama bank...", comment: "")
    static let ccDl = NSLocalizedString("cc.Dl", value: "Tanggal Jatuh Tempo", comment: "")
    static let ccPm = NSLocalizedString("cc.Pm", value: "tiap bulan", comment: "")
    static let ccDue = NSLocalizedString("cc.Due", value: "Deadline", comment: "")
    static let ccS = NSLocalizedString("cc.S", value: "Simpen Kartu", comment: "")
    static let ccNp = NSLocalizedString("cc.Np", value: "0000 0000 0000 0000", comment: "")
    static let ccDp = NSLocalizedString("cc.Dp", value: "15", comment: "")
    static let ccDf = NSLocalizedString("cc.Df", value: "Tgl %d", comment: "")

    // MARK: - em
    static let emT = NSLocalizedString("em.T", value: "Kalkulator EMI", comment: "")
    static let emLl = NSLocalizedString("em.Ll", value: "Nominal Pinjaman (Rp)", comment: "")
    static let emTl = NSLocalizedString("em.Tl", value: "Lama Cicilan (Bulan)", comment: "")
    static let emRl = NSLocalizedString("em.Rl", value: "Bunga per Tahun", comment: "")
    static let emCa = NSLocalizedString("em.Ca", value: "Hitung Cicilan", comment: "")
    static let emMe = NSLocalizedString("em.Me", value: "Cicilan Bulanan (EMI)", comment: "")
    static let emTp = NSLocalizedString("em.Tp", value: "Total Bayar", comment: "")
    static let emTi = NSLocalizedString("em.Ti", value: "Total Bunga Dibayar", comment: "")
    static let emFo = NSLocalizedString("em.Fo", value: "Cara Hitung EMI:", comment: "")
    static let emLp = NSLocalizedString("em.Lp", value: "Contoh: 50000000", comment: "")
    static let emTenp = NSLocalizedString("em.Tenp", value: "Contoh: 24", comment: "")
    static let emRp = NSLocalizedString("em.Rp", value: "Contoh: 12", comment: "")
    static let emTs = NSLocalizedString("em.Ts", value: "bulan", comment: "")
    static let emRs = NSLocalizedString("em.Rs", value: "% / tahun", comment: "")

    // MARK: - ml
    static let mlT = NSLocalizedString("ml.T", value: "Maksimal Pinjaman", comment: "")
    static let mlPl = NSLocalizedString("ml.Pl", value: "Cicilan Per Bulan (Rp)", comment: "")
    static let mlRl = NSLocalizedString("ml.Rl", value: "Bunga per Tahun", comment: "")
    static let mlTl = NSLocalizedString("ml.Tl", value: "Lama Pinjaman", comment: "")
    static let mlCa = NSLocalizedString("ml.Ca", value: "Hitung Maks Pinjaman", comment: "")
    static let mlRla = NSLocalizedString("ml.Rla", value: "Estimasi Maksimal Pinjaman Kamu", comment: "")
    static let mlNo = NSLocalizedString("ml.No", value: "Catatan:", comment: "")
    static let mlIt = NSLocalizedString("ml.It", value: "Isi jumlah cicilan yang sanggup kamu bayar per bulan, nanti kami hitungkan maksimal pinjamannya.", comment: "")
    static let mlRs = NSLocalizedString("ml.Rs", value: "Cicilan %@ per bulan, tenor %@ bulan, bunga %@%% per tahun", comment: "")
    static let mlDi = NSLocalizedString("ml.Di", value: "Ini cuma estimasi hitungan matematika ya. Pihak bank bisa punya syarat tambahan kayak skor kredit dan riwayat keuangan kamu.", comment: "")
    static let mlPp = NSLocalizedString("ml.Pp", value: "Contoh: 2000000", comment: "")
    static let mlRp = NSLocalizedString("ml.Rp", value: "Contoh: 12", comment: "")
    static let mlTp = NSLocalizedString("ml.Tp", value: "Contoh: 36", comment: "")
    static let mlTs = NSLocalizedString("ml.Ts", value: "bulan", comment: "")
    static let mlRsu = NSLocalizedString("ml.Rsu", value: "% / tahun", comment: "")

    // MARK: - er
    static let erT = NSLocalizedString("er.T", value: "Kurs Mata Uang", comment: "")
    static let erIl = NSLocalizedString("er.Il", value: "Nominal Rupiah (IDR)", comment: "")
    static let erRt = NSLocalizedString("er.Rt", value: "Hasil Tukar", comment: "")
    static let erSc = NSLocalizedString("er.Sc", value: "Pilih Mata Uang", comment: "")
    static let erDi = NSLocalizedString("er.Di", value: "* Kurs bisa berubah tiap saat ya, ini cuma patokan.", comment: "")

    // MARK: - an
    static let anT = NSLocalizedString("an.T", value: "Analisis Keuangan 📈", comment: "")
    static let anTi = NSLocalizedString("an.Ti", value: "Total Uang Masuk", comment: "")
    static let anTe = NSLocalizedString("an.Te", value: "Total Uang Keluar", comment: "")
    static let anSr = NSLocalizedString("an.Sr", value: "Persentase Nabung", comment: "")
    static let anOi = NSLocalizedString("an.Oi", value: "dari total uang masuk", comment: "")
    static let anEc = NSLocalizedString("an.Ec", value: "Pengeluaran per Kategori 📂", comment: "")
    static let anIv = NSLocalizedString("an.Iv", value: "Uang Masuk vs Keluar", comment: "")
    static let anTo = NSLocalizedString("an.To", value: "Top Pengeluaran", comment: "")
    static let anNd = NSLocalizedString("an.Nd", value: "Belum ada pengeluaran nih", comment: "")
    static let anNm = NSLocalizedString("an.Nm", value: "Blm ada pengeluaran bulan ini nih", comment: "")

    // MARK: - pf
    static let pfTr = NSLocalizedString("pf.Tr", value: "Transaksi", comment: "")
    static let pfCc = NSLocalizedString("pf.Cc", value: "Kartu Kredit", comment: "")
    static let pfRm = NSLocalizedString("pf.Rm", value: "Pengingat", comment: "")
    static let pfCu = NSLocalizedString("pf.Cu", value: "Kontak Kami", comment: "")
    static let pfPr = NSLocalizedString("pf.Pr", value: "Kebijakan Privasi", comment: "")
    static let pfRa = NSLocalizedString("pf.Ra", value: "Kasih Rating", comment: "")
    static let pfSe = NSLocalizedString("pf.Se", value: "Setelan", comment: "")
    static let pfCn = NSLocalizedString("pf.Cn", value: "Ganti Nama", comment: "")
    static let pfNp = NSLocalizedString("pf.Np", value: "Nama Kamu", comment: "")
    static let pfNm = NSLocalizedString("pf.Nm", value: "Tulis nama panggilan kamu di sini", comment: "")
    static let pfAt = NSLocalizedString("pf.At", value: "Pasang Foto", comment: "")
    static let pfTp = NSLocalizedString("pf.Tp", value: "Jepret Foto", comment: "")
    static let pfPg = NSLocalizedString("pf.Pg", value: "Cari dari Galeri", comment: "")

    // MARK: - st
    static let stT = NSLocalizedString("st.T", value: "Setelan", comment: "")
    static let stAi = NSLocalizedString("st.Ai", value: "Informasi", comment: "")
    static let stV = NSLocalizedString("st.V", value: "Versi App", comment: "")
    static let stDz = NSLocalizedString("st.Dz", value: "Zona Bahaya ⚠️", comment: "")
    static let stLo = NSLocalizedString("st.Lo", value: "Logout Akun", comment: "")
    static let stDd = NSLocalizedString("st.Dd", value: "Hapus Seluruh Data", comment: "")
    static let stLt = NSLocalizedString("st.Lt", value: "Yakin Logout?", comment: "")
    static let stLm = NSLocalizedString("st.Lm", value: "Kamu akan logout dari aplikasi. Tenang aja, semua data tetap aman tersimpan.", comment: "")
    static let stDt = NSLocalizedString("st.Dt", value: "⚠️ Hapus Data Akun?", comment: "")
    static let stDm = NSLocalizedString("st.Dm", value: "Aksi ini permanen dan gak bisa di-undo. Seluruh data transaksi, reminder, dan kartu kredit bakal dihapus selamanya.", comment: "")
    static let stDs = NSLocalizedString("st.Ds", value: "⚠️ Konfirmasi Ulang", comment: "")
    static let stDsm = NSLocalizedString("st.Dsm", value: "Sekali lagi ya, data yang dihapus gak bisa balik. Yakin mau lanjut?", comment: "")
    static let stLc = NSLocalizedString("st.Lc", value: "Keluar", comment: "")
    static let stDc = NSLocalizedString("st.Dc", value: "Hapus Akun ❌", comment: "")
    static let stDsc = NSLocalizedString("st.Dsc", value: "Hapus Selamanya ❌", comment: "")
    static let stAl = NSLocalizedString("st.Al", value: "Udah versi paling baru nih", comment: "")

    // MARK: - cn
    static let cnT = NSLocalizedString("cn.T", value: "Kontak Kami", comment: "")
    static let cnMl = NSLocalizedString("cn.Ml", value: "Isi Pesan", comment: "")
    static let cnAl = NSLocalizedString("cn.Al", value: "Lampiran (optional)", comment: "")
    static let cnAi = NSLocalizedString("cn.Ai", value: "Tambah Foto", comment: "")
    static let cnCp = NSLocalizedString("cn.Cp", value: "Tulis email atau nomor WhatsApp kamu", comment: "")
    static let cnCl = NSLocalizedString("cn.Cl", value: "Email atau WA", comment: "")
    static let cnSu = NSLocalizedString("cn.Su", value: "Kirim", comment: "")
    static let cnSg = NSLocalizedString("cn.Sg", value: "Ngirim dulu...", comment: "")
    static let cnSm = NSLocalizedString("cn.Sm", value: "Pesan terkirim! Tim kami bakal segera follow-up ya.", comment: "")
    static let cnAs = NSLocalizedString("cn.As", value: "Lampiran", comment: "")
    static let cnVl = NSLocalizedString("cn.Vl", value: "Video (optional)", comment: "")
    static let cnAv = NSLocalizedString("cn.Av", value: "Tambah Video 🎥", comment: "")
    static let cnVs = NSLocalizedString("cn.Vs", value: "Video", comment: "")
    static let cnRv = NSLocalizedString("cn.Rv", value: "Rekam Sekarang", comment: "")
    static let cnPv = NSLocalizedString("cn.Pv", value: "Cari dari Galeri", comment: "")
}
