import Foundation

/// 文案
enum AllStr {
    // MARK: - Error
    static let errorServerUnavailable = NSLocalizedString("error.serverUnavailable", value: "Layanan sedang ramai, coba lagi nanti ya", comment: "")

    // MARK: - Launch
    static let launchAppName = NSLocalizedString("launch.appName", value: "Catat DanaKu", comment: "")
    static let launchTagline = NSLocalizedString("launch.tagline", value: "Pantau keuanganmu, simpel aja", comment: "")

    // MARK: - Privacy
    static let privacyAgree = NSLocalizedString("privacy.agree", value: "Setuju", comment: "")
    static let privacyDisagree = NSLocalizedString("privacy.disagree", value: "Tidak Setuju", comment: "")
    static let privacyAlertMessage = NSLocalizedString("privacy.alert", value: "Setujui dulu kebijakan privasi supaya bisa lanjut, ya", comment: "")
    static let privacyAlertOK = NSLocalizedString("privacy.alertOK", value: "OK", comment: "")
    static let privacyDescription = NSLocalizedString("privacy.description", value: "Baca dan setujui dulu kebijakan privasi di bawah ini, ya.", comment: "")
    static let privacyToastWait = NSLocalizedString("privacy.toastWait", value: "Sebentar ya, halaman privasi masih dimuat.", comment: "")

    // MARK: - Login
    static let loginPhoneHint = NSLocalizedString("login.phoneHint", value: "Nomor HP kamu", comment: "")
    static let loginCodeHint = NSLocalizedString("login.codeHint", value: "Kode OTP", comment: "")
    static let loginSendCode = NSLocalizedString("login.sendCode", value: "Minta Kode", comment: "")
    static let loginWaLogin = NSLocalizedString("login.waLogin", value: "Kirim kode lewat WhatsApp", comment: "")
    static let loginSmsLogin = NSLocalizedString("login.smsLogin", value: "Kirim kode lewat SMS", comment: "")
    static let loginWaHint = NSLocalizedString("login.waHint", value: "*Kode verifikasi bakal dikirim lewat WhatsApp ya.", comment: "")
    static let loginSentToSms = NSLocalizedString("login.sentToSms", value: "Kode sudah dikirim ke SMS kamu, cek ya.", comment: "")
    static let loginSentToWa = NSLocalizedString("login.sentToWa", value: "Kode sudah dikirim ke WhatsApp kamu, cek ya.", comment: "")
    static let loginResendViaWa = NSLocalizedString("login.resendViaWa", value: "Belum dapat kode? Coba lewat WhatsApp aja.", comment: "")
    static let loginResendViaSms = NSLocalizedString("login.resendViaSms", value: "Belum dapat kode? Coba lewat SMS aja.", comment: "")
    static let loginPrivacyPrefix = NSLocalizedString("login.privacyPrefix", value: "Pastikan kamu setuju dengan ", comment: "")
    static let loginPrivacyLink = NSLocalizedString("login.privacyLink", value: "kebijakan privasi", comment: "")
    static let loginPrivacySuffix = NSLocalizedString("login.privacySuffix", value: " kami", comment: "")
    static let loginInvalidPhone = NSLocalizedString("login.invalidPhone", value: "Masukkan nomor HP yang benar dulu ya.", comment: "")
    static let loginInvalidCode = NSLocalizedString("login.invalidCode", value: "Isi kode verifikasi 4 digit yang dikirim ya.", comment: "")
    static let loginLoginButton = NSLocalizedString("login.loginButton", value: "Masuk", comment: "")
    static let loginTitle = NSLocalizedString("login.title", value: "Login / Daftar", comment: "")
    static let loginCountryCode = NSLocalizedString("login.countryCode", value: "+62", comment: "")
    static let loginPrivacySheetTitle = NSLocalizedString("login.privacySheetTitle", value: "Kebijakan Privasi", comment: "")
    static let loginClose = NSLocalizedString("login.close", value: "Tutup", comment: "")

    // MARK: - Permission
    static let permissionCameraTitle = NSLocalizedString("permission.cameraTitle", value: "Akses Kamera", comment: "")
    static let permissionCameraMessage = NSLocalizedString("permission.cameraMessage", value: "Supaya aplikasi berjalan maksimal, buka Pengaturan dan aktifkan izin kameranya dulu ya. Makasih!", comment: "")
    static let permissionGo = NSLocalizedString("permission.go", value: "Ke Pengaturan", comment: "")
    static let permissionCancel = NSLocalizedString("permission.cancel", value: "Gak Jadi", comment: "")

    // MARK: - Common
    static let commonSave = NSLocalizedString("common.save", value: "Simpen", comment: "")
    static let commonCancel = NSLocalizedString("common.cancel", value: "Gak Jadi", comment: "")
    static let commonIncome = NSLocalizedString("common.income", value: "Uang Masuk", comment: "")
    static let commonExpense = NSLocalizedString("common.expense", value: "Uang Keluar", comment: "")
    static let commonAmount = NSLocalizedString("common.amount", value: "Nominal", comment: "")
    static let commonNote = NSLocalizedString("common.note", value: "Keterangan", comment: "")
    static let commonLocation = NSLocalizedString("common.location", value: "Tempat", comment: "")
    static let commonSaved = NSLocalizedString("common.saved", value: "Tersimpan! ✅", comment: "")

    // MARK: - Home
    static let homeWelcome = NSLocalizedString("home.welcome", value: "Selamat datang,", comment: "")
    static let homeMonthlyBalance = NSLocalizedString("home.monthlyBalance", value: "Saldo Bulan Ini 💰", comment: "")
    static let homeViewAnalysis = NSLocalizedString("home.viewAnalysis", value: "Cek analisis →", comment: "")
    static let homeMainFeatures = NSLocalizedString("home.mainFeatures", value: "Layanan Kami", comment: "")
    static let homeRecentTransactions = NSLocalizedString("home.recentTransactions", value: "Transaksi Terbaru", comment: "")
    static let homeViewAll = NSLocalizedString("home.viewAll", value: "Lihat semua →", comment: "")
    static let homeNoTransactions = NSLocalizedString("home.noTransactions", value: "Belum ada transaksi nih", comment: "")
    static let homeTabHome = NSLocalizedString("home.tabHome", value: "Beranda", comment: "")
    static let homeTabProfile = NSLocalizedString("home.tabProfile", value: "Saya", comment: "")
    static let homeFeatureRecord = NSLocalizedString("home.featureRecord", value: "Input Transaksi", comment: "")
    static let homeFeatureReminder = NSLocalizedString("home.featureReminder", value: "Reminder Cicilan", comment: "")
    static let homeFeatureCreditCard = NSLocalizedString("home.featureCreditCard", value: "Kartu Kredit 💳", comment: "")
    static let homeFeatureEMI = NSLocalizedString("home.featureEMI", value: "Kalkulator EMI 📊", comment: "")
    static let homeFeatureMaxLoan = NSLocalizedString("home.featureMaxLoan", value: "Batas Pinjaman", comment: "")
    static let homeFeatureExchange = NSLocalizedString("home.featureExchange", value: "Kurs Mata Uang 💱", comment: "")
    static let homeFeatureAnalysis = NSLocalizedString("home.featureAnalysis", value: "Analisis Keuangan 📈", comment: "")

    // MARK: - RecordTransaction
    static let recordTransactionTitle = NSLocalizedString("record.title", value: "Input Transaksi", comment: "")
    static let recordTransactionSave = NSLocalizedString("record.save", value: "Simpen Transaksi", comment: "")
    static let recordTransactionLocationPlaceholder = NSLocalizedString("record.locationPlaceholder", value: "Isi tempat...", comment: "")
    static let recordTransactionNotePlaceholder = NSLocalizedString("record.notePlaceholder", value: "Tulis keterangan...", comment: "")
    static let recordTransactionPhotoTitle = NSLocalizedString("record.photoTitle", value: "Lampirkan Bukti", comment: "")
    static let recordTransactionPhotoAttached = NSLocalizedString("record.photoAttached", value: "Bukti terlampir ✅", comment: "")
    static let recordTransactionTakePhoto = NSLocalizedString("record.takePhoto", value: "Jepret / Cari Foto", comment: "")
    static let recordTransactionCategory = NSLocalizedString("record.category", value: "Kategori 📂", comment: "")
    static let recordTransactionSavedToast = NSLocalizedString("record.savedToast", value: "Tersimpan! ✅", comment: "")

    // MARK: - TransactionDetail
    static let transactionDetailTitle = NSLocalizedString("detail.title", value: "Rincian Transaksi", comment: "")
    static let transactionDetailType = NSLocalizedString("detail.type", value: "Jenis", comment: "")
    static let transactionDetailCategory = NSLocalizedString("detail.category", value: "Kategori 📂", comment: "")
    static let transactionDetailAmount = NSLocalizedString("detail.amount", value: "Nominal", comment: "")
    static let transactionDetailDate = NSLocalizedString("detail.date", value: "Tgl", comment: "")
    static let transactionDetailLocation = NSLocalizedString("detail.location", value: "Tempat", comment: "")
    static let transactionDetailNote = NSLocalizedString("detail.note", value: "Keterangan", comment: "")
    static let transactionDetailPhoto = NSLocalizedString("detail.photo", value: "Lampiran Bukti", comment: "")

    // MARK: - Category
    // Expense
    static let categoryFood = NSLocalizedString("category.food", value: "Makanan", comment: "")
    static let categoryTransport = NSLocalizedString("category.transport", value: "Transportasi", comment: "")
    static let categoryShopping = NSLocalizedString("category.shopping", value: "Belanja", comment: "")
    static let categoryHealth = NSLocalizedString("category.health", value: "Kesehatan", comment: "")
    static let categoryEntertainment = NSLocalizedString("category.entertainment", value: "Hiburan", comment: "")
    static let categoryEducation = NSLocalizedString("category.education", value: "Pendidikan", comment: "")
    static let categoryUtilities = NSLocalizedString("category.utilities", value: "Utilitas", comment: "")
    static let categoryOtherExpense = NSLocalizedString("category.otherExpense", value: "Lainnya", comment: "")
    static let categoryGroceries = NSLocalizedString("category.groceries", value: "Sembako", comment: "")
    static let categoryHousing = NSLocalizedString("category.housing", value: "Perumahan/Sewa", comment: "")
    static let categoryCommunication = NSLocalizedString("category.communication", value: "Pulsa & Internet", comment: "")
    static let categoryFamily = NSLocalizedString("category.family", value: "Keluarga & Anak", comment: "")
    static let categoryInsurance = NSLocalizedString("category.insurance", value: "Asuransi", comment: "")
    static let categoryPets = NSLocalizedString("category.pets", value: "Hewan Peliharaan", comment: "")
    static let categorySubscriptions = NSLocalizedString("category.subscriptions", value: "Langganan", comment: "")
    static let categoryPersonalCare = NSLocalizedString("category.personalCare", value: "Perawatan Diri", comment: "")
    static let categoryGifts = NSLocalizedString("category.gifts", value: "Hadiah & Donasi", comment: "")
    static let categoryTravel = NSLocalizedString("category.travel", value: "Perjalanan/Wisata", comment: "")
    // Income
    static let categorySalary = NSLocalizedString("category.salary", value: "Gaji", comment: "")
    static let categoryInvestment = NSLocalizedString("category.investment", value: "Pendapatan Investasi", comment: "")
    static let categoryRental = NSLocalizedString("category.rental", value: "Aset/Pendapatan Sewa", comment: "")
    static let categoryPrize = NSLocalizedString("category.prize", value: "Kemenangan/Hadiah", comment: "")
    static let categoryProject = NSLocalizedString("category.project", value: "Proyek Jangka Pendek", comment: "")
    static let categoryBusiness = NSLocalizedString("category.business", value: "Pendapatan Bisnis", comment: "")
    static let categorySale = NSLocalizedString("category.sale", value: "Penjualan Barang", comment: "")
    static let categoryGift = NSLocalizedString("category.gift", value: "Uang Hadiah/Hibah", comment: "")
    static let categoryOtherIncome = NSLocalizedString("category.otherIncome", value: "Lainnya", comment: "")

    // MARK: - Reminder
    static let reminderTitle = NSLocalizedString("reminder.title", value: "Reminder Cicilan", comment: "")
    static let reminderMonthlyTotal = NSLocalizedString("reminder.monthlyTotal", value: "Total Cicilan Bulan Ini", comment: "")
    static let reminderActiveCount = NSLocalizedString("reminder.activeCount", value: "reminder aktif", comment: "")
    static let reminderNoReminders = NSLocalizedString("reminder.noReminders", value: "Belum ada pengingat nih", comment: "")
    static let reminderUrgent = NSLocalizedString("reminder.urgent", value: "Urgent 🔴", comment: "")
    static let reminderPastDue = NSLocalizedString("reminder.pastDue", value: "Sudah lewat deadline", comment: "")
    static let reminderAddTitle = NSLocalizedString("reminder.addTitle", value: "Buat Reminder Baru", comment: "")
    static let reminderNameLabel = NSLocalizedString("reminder.nameLabel", value: "Nama Cicilan", comment: "")
    static let reminderAmountLabel = NSLocalizedString("reminder.amountLabel", value: "Jumlah (Rp)", comment: "")
    static let reminderDueDateLabel = NSLocalizedString("reminder.dueDateLabel", value: "Tanggal Jatuh Tempo", comment: "")
    static let reminderNoteLabel = NSLocalizedString("reminder.noteLabel", value: "Keterangan", comment: "")
    static let reminderNamePlaceholder = NSLocalizedString("reminder.namePlaceholder", value: "Contoh: Cicilan KPR", comment: "")
    static let reminderAmountPlaceholder = NSLocalizedString("reminder.amountPlaceholder", value: "Contoh: 2000000", comment: "")
    static let reminderNotePlaceholder = NSLocalizedString("reminder.notePlaceholder", value: "Contoh: Bank BCA", comment: "")

    // MARK: - CreditCard
    static let creditCardTitle = NSLocalizedString("creditcard.title", value: "Kartu Kredit 💳", comment: "")
    static let creditCardEmpty = NSLocalizedString("creditcard.empty", value: "Belum ada kartu yang disimpan nih", comment: "")
    static let creditCardAddTitle = NSLocalizedString("creditcard.addTitle", value: "Buat Kartu Baru", comment: "")
    static let creditCardNumberLabel = NSLocalizedString("creditcard.numberLabel", value: "No. Kartu", comment: "")
    static let creditCardBankLabel = NSLocalizedString("creditcard.bankLabel", value: "Bank", comment: "")
    static let creditCardBankPlaceholder = NSLocalizedString("creditcard.bankPlaceholder", value: "Atau tulis nama bank...", comment: "")
    static let creditCardDueDateLabel = NSLocalizedString("creditcard.dueDateLabel", value: "Tanggal Jatuh Tempo", comment: "")
    static let creditCardPerMonth = NSLocalizedString("creditcard.perMonth", value: "tiap bulan", comment: "")
    static let creditCardDueLabel = NSLocalizedString("creditcard.dueLabel", value: "Deadline", comment: "")
    static let creditCardSave = NSLocalizedString("creditcard.save", value: "Simpen Kartu", comment: "")
    static let creditCardNumberPlaceholder = NSLocalizedString("creditcard.numberPlaceholder", value: "0000 0000 0000 0000", comment: "")
    static let creditCardDatePlaceholder = NSLocalizedString("creditcard.datePlaceholder", value: "15", comment: "")
    static let creditCardDateFormat = NSLocalizedString("creditcard.dateFormat", value: "Tgl %d", comment: "")

    // MARK: - EMI
    static let emiTitle = NSLocalizedString("emi.title", value: "Kalkulator EMI 📊", comment: "")
    static let emiLoanLabel = NSLocalizedString("emi.loanLabel", value: "Nominal Pinjaman (Rp)", comment: "")
    static let emiTenorLabel = NSLocalizedString("emi.tenorLabel", value: "Lama Cicilan (Bulan)", comment: "")
    static let emiRateLabel = NSLocalizedString("emi.rateLabel", value: "Bunga per Tahun", comment: "")
    static let emiCalculate = NSLocalizedString("emi.calculate", value: "Hitung Cicilan", comment: "")
    static let emiMonthlyEMI = NSLocalizedString("emi.monthlyEMI", value: "Cicilan Bulanan (EMI)", comment: "")
    static let emiTotalPayment = NSLocalizedString("emi.totalPayment", value: "Total Bayar", comment: "")
    static let emiTotalInterest = NSLocalizedString("emi.totalInterest", value: "Total Bunga Dibayar", comment: "")
    static let emiFormula = NSLocalizedString("emi.formula", value: "Cara Hitung EMI:", comment: "")
    static let emiLoanPlaceholder = NSLocalizedString("emi.loanPlaceholder", value: "Contoh: 50000000", comment: "")
    static let emiTenorPlaceholder = NSLocalizedString("emi.tenorPlaceholder", value: "Contoh: 24", comment: "")
    static let emiRatePlaceholder = NSLocalizedString("emi.ratePlaceholder", value: "Contoh: 12", comment: "")
    static let emiTenorSuffix = NSLocalizedString("emi.tenorSuffix", value: "bulan", comment: "")
    static let emiRateSuffix = NSLocalizedString("emi.rateSuffix", value: "% / tahun", comment: "")

    // MARK: - MaxLoan
    static let maxLoanTitle = NSLocalizedString("maxloan.title", value: "Maksimal Pinjaman", comment: "")
    static let maxLoanPaymentLabel = NSLocalizedString("maxloan.paymentLabel", value: "Cicilan Per Bulan (Rp)", comment: "")
    static let maxLoanRateLabel = NSLocalizedString("maxloan.rateLabel", value: "Bunga per Tahun", comment: "")
    static let maxLoanTenorLabel = NSLocalizedString("maxloan.tenorLabel", value: "Lama Pinjaman", comment: "")
    static let maxLoanCalculate = NSLocalizedString("maxloan.calculate", value: "Hitung Maks Pinjaman", comment: "")
    static let maxLoanResultLabel = NSLocalizedString("maxloan.resultLabel", value: "Estimasi Maksimal Pinjaman Kamu", comment: "")
    static let maxLoanNote = NSLocalizedString("maxloan.note", value: "Catatan:", comment: "")
    static let maxLoanInfoTip = NSLocalizedString("maxloan.infoTip", value: "Isi jumlah cicilan yang sanggup kamu bayar per bulan, nanti kami hitungkan maksimal pinjamannya.", comment: "")
    static let maxLoanResultSummary = NSLocalizedString("maxloan.resultSummary", value: "Cicilan %@ per bulan, tenor %@ bulan, bunga %@%% per tahun", comment: "")
    static let maxLoanDisclaimer = NSLocalizedString("maxloan.disclaimer", value: "Ini cuma estimasi hitungan matematika ya. Pihak bank bisa punya syarat tambahan kayak skor kredit dan riwayat keuangan kamu.", comment: "")
    static let maxLoanPaymentPlaceholder = NSLocalizedString("maxloan.paymentPlaceholder", value: "Contoh: 2000000", comment: "")
    static let maxLoanRatePlaceholder = NSLocalizedString("maxloan.ratePlaceholder", value: "Contoh: 12", comment: "")
    static let maxLoanTenorPlaceholder = NSLocalizedString("maxloan.tenorPlaceholder", value: "Contoh: 36", comment: "")
    static let maxLoanTenorSuffix = NSLocalizedString("maxloan.tenorSuffix", value: "bulan", comment: "")
    static let maxLoanRateSuffix = NSLocalizedString("maxloan.rateSuffix", value: "% / tahun", comment: "")

    // MARK: - ExchangeRate
    static let exchangeRateTitle = NSLocalizedString("exchange.title", value: "Kurs Mata Uang 💱", comment: "")
    static let exchangeRateIdrLabel = NSLocalizedString("exchange.idrLabel", value: "Nominal Rupiah (IDR)", comment: "")
    static let exchangeRateResultTitle = NSLocalizedString("exchange.resultTitle", value: "Hasil Tukar", comment: "")
    static let exchangeRateSelectCurrency = NSLocalizedString("exchange.selectCurrency", value: "Pilih Mata Uang", comment: "")
    static let exchangeRateDisclaimer = NSLocalizedString("exchange.disclaimer", value: "* Kurs bisa berubah tiap saat ya, ini cuma patokan.", comment: "")

    // MARK: - Analysis
    static let analysisTitle = NSLocalizedString("analysis.title", value: "Analisis Keuangan 📈", comment: "")
    static let analysisTotalIncome = NSLocalizedString("analysis.totalIncome", value: "Total Uang Masuk", comment: "")
    static let analysisTotalExpense = NSLocalizedString("analysis.totalExpense", value: "Total Uang Keluar", comment: "")
    static let analysisSavingsRate = NSLocalizedString("analysis.savingsRate", value: "Persentase Nabung", comment: "")
    static let analysisOfIncome = NSLocalizedString("analysis.ofIncome", value: "dari total uang masuk", comment: "")
    static let analysisExpenseByCategory = NSLocalizedString("analysis.expenseByCategory", value: "Pengeluaran per Kategori 📂", comment: "")
    static let analysisIncomeVsExpense = NSLocalizedString("analysis.incomeVsExpense", value: "Uang Masuk vs Keluar", comment: "")
    static let analysisTopExpenses = NSLocalizedString("analysis.topExpenses", value: "Top Pengeluaran", comment: "")
    static let analysisNoExpenseData = NSLocalizedString("analysis.noExpenseData", value: "Belum ada pengeluaran nih", comment: "")
    static let analysisNoExpenseDataMonth = NSLocalizedString("analysis.noExpenseDataMonth", value: "Blm ada pengeluaran bulan ini nih", comment: "")

    // MARK: - Profile
    static let profileTransactions = NSLocalizedString("profile.transactions", value: "Transaksi", comment: "")
    static let profileCreditCards = NSLocalizedString("profile.creditCards", value: "Kartu Kredit 💳", comment: "")
    static let profileReminders = NSLocalizedString("profile.reminders", value: "Pengingat", comment: "")
    static let profileContactUs = NSLocalizedString("profile.contactUs", value: "Kontak Kami", comment: "")
    static let profilePrivacy = NSLocalizedString("profile.privacy", value: "Kebijakan Privasi", comment: "")
    static let profileRateApp = NSLocalizedString("profile.rateApp", value: "Kasih Rating ⭐", comment: "")
    static let profileSettings = NSLocalizedString("profile.settings", value: "Setelan", comment: "")
    static let profileChangeNameTitle = NSLocalizedString("profile.changeNameTitle", value: "Ganti Nama", comment: "")
    static let profileNamePlaceholder = NSLocalizedString("profile.namePlaceholder", value: "Nama Kamu", comment: "")
    static let profileNameMessage = NSLocalizedString("profile.nameMessage", value: "Tulis nama panggilan kamu di sini", comment: "")
    static let profileAvatarTitle = NSLocalizedString("profile.avatarTitle", value: "Pasang Foto", comment: "")
    static let profileTakePhoto = NSLocalizedString("profile.takePhoto", value: "Jepret Foto", comment: "")
    static let profilePickGallery = NSLocalizedString("profile.pickGallery", value: "Cari dari Galeri", comment: "")

    // MARK: - Settings
    static let settingsTitle = NSLocalizedString("settings.title", value: "Setelan", comment: "")
    static let settingsAppInfo = NSLocalizedString("settings.appInfo", value: "Informasi", comment: "")
    static let settingsVersion = NSLocalizedString("settings.version", value: "Versi App", comment: "")
    static let settingsDangerZone = NSLocalizedString("settings.dangerZone", value: "Zona Bahaya ⚠️", comment: "")
    static let settingsLogout = NSLocalizedString("settings.logout", value: "Logout Akun", comment: "")
    static let settingsDeleteData = NSLocalizedString("settings.deleteData", value: "Hapus Seluruh Data", comment: "")
    static let settingsLogoutTitle = NSLocalizedString("settings.logoutTitle", value: "Yakin Logout?", comment: "")
    static let settingsLogoutMessage = NSLocalizedString("settings.logoutMessage", value: "Kamu akan logout dari aplikasi. Tenang aja, semua data tetap aman tersimpan.", comment: "")
    static let settingsDeleteTitle = NSLocalizedString("settings.deleteTitle", value: "⚠️ Hapus Data Akun?", comment: "")
    static let settingsDeleteMessage = NSLocalizedString("settings.deleteMessage", value: "Aksi ini permanen dan gak bisa di-undo. Seluruh data transaksi, reminder, dan kartu kredit bakal dihapus selamanya.", comment: "")
    static let settingsDeleteSecondTitle = NSLocalizedString("settings.deleteSecondTitle", value: "⚠️ Konfirmasi Ulang", comment: "")
    static let settingsDeleteSecondMessage = NSLocalizedString("settings.deleteSecondMessage", value: "Sekali lagi ya, data yang dihapus gak bisa balik. Yakin mau lanjut?", comment: "")
    static let settingsLogoutConfirm = NSLocalizedString("settings.logoutConfirm", value: "Keluar", comment: "")
    static let settingsDeleteConfirm = NSLocalizedString("settings.deleteConfirm", value: "Hapus Akun ❌", comment: "")
    static let settingsDeleteSecondConfirm = NSLocalizedString("settings.deleteSecondConfirm", value: "Hapus Selamanya ❌", comment: "")
    static let settingsAlreadyLatest = NSLocalizedString("settings.alreadyLatest", value: "Udah versi paling baru nih", comment: "")

    // MARK: - Contact
    static let contactTitle = NSLocalizedString("contact.title", value: "Kontak Kami", comment: "")
    static let contactMessageLabel = NSLocalizedString("contact.messageLabel", value: "Isi Pesan", comment: "")
    static let contactAttachmentLabel = NSLocalizedString("contact.attachmentLabel", value: "Lampiran (optional)", comment: "")
    static let contactAddImage = NSLocalizedString("contact.addImage", value: "Tambah Foto", comment: "")
    static let contactContactPlaceholder = NSLocalizedString("contact.contactPlaceholder", value: "Tulis email atau nomor WhatsApp kamu", comment: "")
    static let contactContactLabel = NSLocalizedString("contact.contactLabel", value: "Email atau WA", comment: "")
    static let contactSubmit = NSLocalizedString("contact.submit", value: "Kirim", comment: "")
    static let contactSubmitting = NSLocalizedString("contact.submitting", value: "Ngirim dulu...", comment: "")
    static let contactSuccessMessage = NSLocalizedString("contact.successMessage", value: "Pesan terkirim! Tim kami bakal segera follow-up ya.", comment: "")
    static let contactAttachmentSheet = NSLocalizedString("contact.attachmentSheet", value: "Lampiran", comment: "")
    static let contactVideoLabel = NSLocalizedString("contact.videoLabel", value: "Video (optional)", comment: "")
    static let contactAddVideo = NSLocalizedString("contact.addVideo", value: "Tambah Video 🎥", comment: "")
    static let contactVideoSheet = NSLocalizedString("contact.videoSheet", value: "Video", comment: "")
    static let contactRecordVideo = NSLocalizedString("contact.recordVideo", value: "Rekam Sekarang", comment: "")
    static let contactPickVideo = NSLocalizedString("contact.pickVideo", value: "Cari dari Galeri", comment: "")
}
